// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VLC.RecipeManagment.Infrastructure;

#nullable disable

namespace VLC.RecipeManagment.Migrations
{
	[DbContext(typeof(ApiDbContext))]
	[Migration("20230225232942_init")]
	partial class init
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.3")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

			modelBuilder.Entity("VLC.RecipeManagment.Application.Models.Recipes.Recipe", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

					b.Property<int>("Calories")
						.HasColumnType("int");

					b.Property<string>("Ingredients")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Instructions")
						.HasColumnType("nvarchar(max)");

					b.Property<string>("Label")
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("Recipes");
				});
#pragma warning restore 612, 618
		}
	}
}
